# Choose your lucky block
# default 19 (Sponge)
luckyblock-id: 19

# Choose how big should be
# the unlucky explosion
explosion-min: 1
explosion-max: 3

# Choose how many players are required
# to start the game
needed-players: 4
