# Choose your lucky block
# default 19 (Sponge)
luckyblock-id: 19

# Choose how big should be
# the unlucky explosion
explosion-min: 1
explosion-max: 3

# Choose how many players are required
# to start the game
needed-players: 4

# Popup will be send while waiting
# for other players
# You can also use colors
wait-popup: "ยง6Waiting for players..."

# Place where the game runs
join-world:
join-x:
join-y:
join-z:
