# Choose your lucky block
# default 19 (Sponge)
luckyblock-id: 19

# Choose how big should be
# the unlucky explosion
min-explosion: 1
max-explosion: 3

# Choose how many players are required
# to start the game
needed-players: 4

# Popup will be send while waiting
# for other players
# You can also use colors
wait-popup: "§6Waiting for players..."

# Message will be send if the game
# is not running
game-is-not-running: "§cYou can not break Lucky Blocks while you are not in a game!"

# Will be send to a player if he
# have not the permission to
# use a lucky block
not-allowed-to-use-luckyblock: "§cYou are not allowed to use Lucky Blocks!"

# Place where the game starts
join-x:
join-y:
join-z:
join-world:

# Location of status sign
sign-x:
sign-y:
sign-z:
sign-world:
sign-mode: false
