# Warning: Editing this configuration
# can cause crashes by putting wrong
# information at the wrong place

# Choose your lucky block
# default 19 (Sponge)
luckyblock-id: 19

# Choose how big should be
# the unlucky explosion
min-explosion: 1
max-explosion: 3

# Choose how many players are required
# to start the game
needed-players: 4

# Players who died or won the game will
# be teleported there
respawn-level: world
